[package]
version = "0.3.2"
edition = "2018"
authors = ["Geordon Worley <vadixidav@gmail.com>"]
description = "A library for running simulations on grids"
documentation = "https://docs.rs/gridsim/"
license = "MIT"
name = "gridsim"
repository = "https://github.com/vadixidav/gridsim"

[dependencies]
rayon = "1.0.1"
enum-iterator-derive = "0.1.1"
bincode = { version = "1.0.1", optional = true }
serde = { version = "1.0.70", optional = true }
itertools = { version = "0.7.8", optional = true }
float-ord = "0.2.0"
boolinator = "2.4.0"

[features]
default = ["multinode"]
multinode = ["bincode", "serde", "itertools"]
